### ISSUE TITLE
Release 2.0.0 <Insider>

### ISSUE THREAD

**Issue by IoannisP-ITENG** [faebryk/faebryk#138]
### Feature Request

- [x] merge pytest pr #135
- [x] remove __init__ #136 
- [x] test vco project https://github.com/ruben-iteng/eurorack-super_simple_oscillator/pull/1
- [x] test kicad airnode import
- [x] make pip package (done at release, just change version number) #142 
- [x] check deterministic netlist naming
- [x] move source into src folder #140 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
