### ISSUE TITLE
Roadmap Release 3.0.0

### ISSUE THREAD

**Issue by IoannisP-ITENG** [faebryk/faebryk#139]
### Feature Request

- [ ] Core: High-level graph: Graph should not be on netlist level but link level
- [ ] Importer: Kicad schematic importer heuristics
- [ ] Lib: Online services auto importer
- [ ] ...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IoannisP-ITENG** [comment]
When done move into a project
