### ISSUE TITLE
[Meta]: Todo list

### ISSUE THREAD

**Issue by ruben-iteng** [faebryk/faebryk#39]
### Feature Request

# To-Do:
- [ ] core
  - [ ] experiment with improving trait system
- [ ] library
  - [ ] split library
- [ ] Coding convention
  - [ ] compA.vcc.connect(compB.vcc) or CompB.vcc.connect(compA.vcc)
  - [ ] project setup & file structure
  - [ ] [WIP] code of conduct
  - [ ] [WIP] contribution guidelines
- [ ] examples
  - [ ] pinmapping example in library
  - [ ] full stack project
    - [ ] show all implementented functions
  - [ ] MVP project
    - [ ] can be template to start a project from scratch
- [ ] integration
  - [ ] kicad
    - [ ] library integration
      - [ ] wrapper for kicad symbols/footprints/etc
      - [ ] conversion scripts to from kicad libs
    - [ ] pcbnew integration
      - [ ] call pcbnew directly on netlist
      - [ ] potentially invoke autorouter
      - ...
- [ ] graph
  - [ ] make graph more powerful by encapsulating more information into nodes and edges
~ [ ] constraint system
- [ ] exporters
  - [ ] non netlist generators: Come up with & implement other byproducts of faebryk next to a netlist
  - [ ] netlist
    - [ ] [EDIF](https://en.wikipedia.org/wiki/EDIF)
    - [x] kicad
    - [ ] other EDA's
- [ ] Error handling
- [ ] Tooling
  - [ ] better graph visualization
- [ ] Test Framework
  - [ ] Setup tests for library (maybe just use samples?)
- [ ] meta
  - [x] logo
  - [ ] reserve names
    - [ ] website
    - [x] pip
    - [ ] ...
  - [ ] discord integrations
    - [ ] github
  - [ ] surveys

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
